### ISSUE TITLE
[Feat] 맛집 평가 기능 구현

### ISSUE THREAD

**Issue by HyungcheolSim** [Teemo-Wanted/GIS_Restaurant_Service#8]
## 📝 개요
- 평가 기능 구현

## ✅ TO-DO
- [X] 평가 Entity 생성
- [X] 평가 API 구현
- [ ] 맛집에 대해 평점을 업데이트(맛집 모든 평가 기록 조회 및 평균 계산)
- [ ] 로그인한 유저의 토큰정보를 바탕으로 평가 API 동작하도록 수정

## 📌 ETC
- 평가 API 요구사항
<html>
<body>
<h3>평가</h3>

필드 | 속성 | 설명 | 예시 값
-- | -- | -- | --
유저 | fk | 평가를 생성한 유저 FK | 1
맛집 | fk | 유저가 평가한 대상 맛집 FK | 1
점수 | integer | 0 ~ 5 에 해당하는 점수 | 5
내용 | string | 평가 내용이며 0~255자 이내 작성 | 맛있어요!

<ul>
<li>맛집 평가(API)</li>
<li>평점 기능
<ul>
<li>유저가 맛집 평가함</li>
<li>맛집에 대해 평점을 업데이트 함</li>
<li>맛집 모든 평가 기록 조회 및 평균 계산
<ul>
<li>평가 데이터 생성 시 이벤트 발생 → 평점 계산 업데이트 (?)</li>
</ul>
</li>
</ul>
</li>
</ul>

</body>
</html>
